### ISSUE TITLE
Apresentação Destructuring

### ISSUE THREAD

**Issue by lucianacampello** [pitangagile/javascript-path#5]
Disponível a partir do ES6 com o destructuring podemos quebrar estruturas complexas, como arrays e objetos, em estruturas mais simples. É possível estabelecer valores padrão, caso a estrutura não contenha o atributo declarado, renomear atributos vindos de objetos, fazer troca de valores ou pular posições de arrays. 

Referência:
[Destructuring Guide](https://codeburst.io/es6-destructuring-the-complete-guide-7f842d08b98f)

**Comment by ItaloSa** [comment]
Show! Tu pode abrir um PR de acordo com o [Subindo um exemplo](https://github.com/pitangagile/javascript-path/blob/master/CONTRIBUTING.md#subindo-um-exemplo). Qualquer dúvida ou precisar de ajuda pode falar.

**Comment by ItaloSa** [comment]
@lucianacampello ainda esperamos o seu novo PR com o assunto.
